name: Deploy
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        

                  - name: Get npm cache
                    id: cache
                    uses: actions/cache@v2
                    with:
                          path: node_modules
                          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                          restore-keys: |
                                ${{ runner.os }}-node-

                  - name: Install
                    if: steps.cache.outputs.cache-hit != 'true'
                    run: npm install

                  - name: Build
                    run: npm run build

       - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "picpic"
          entrypoint: https://deno.land/std/http/file_server.ts
